### ISSUE TITLE
Allow user access in conn

### ISSUE THREAD

**Issue by anandtrex** [jpiepkow/accesspass#1]
AccessPass has so far been the only library that has exactly what I need for API auth, and has worked out of the box! One thing it's missing is being able to access the details of the user that was authenticated in the connection object in my controllers. It would be great if this could be added. Unfortunately, I don't know enough about meta-programming in elixir to add it myself.

**Comment by jpiepkow** [comment]
changed username to user_id here 755c06305c8f7cac0faa0378538b92675a8aabfa

Thanks for the issue!

**Comment by anandtrex** [comment]
Great thanks! I could look at adding `user_id` into `user.meta` inside `user.ex` in a few days when I get time.
