### ISSUE TITLE
Optional URL for email templates

### ISSUE THREAD

**Issue by dfalling** [jpiepkow/accesspass#16]
It would be great if it was possible add a root URL to configs to be injected into the email templates.  Currently I have to customize these manually, which is a bit messy with other fields like `conf_key`, `password_key`, and `user_name` being replaced automatically.

My use case is for testing the entire process on my local environment with a localhost URL before pushing code to prod.

**Comment by jpiepkow** [comment]
I completely agree and will most likely get to this change tonight plus a couple of the other issues open.

**Comment by dfalling** [comment]
Awesome, thank you!  I'll test it out as soon as it's in.

**Comment by jpiepkow** [comment]
base_url has been added as a config option. Note that the email confirmation is a post endpoint so you will need some ui set to handle the email redirect anyways but you can now set it to localhost or whatever you need.

Also with the latest version I went through a couple other open issues and how you do hooks/email templateing has changed so you may want to check the docs again if you were using any of that.

**Comment by jpiepkow** [comment]
https://github.com/jpiepkow/accesspass/releases/tag/0.5.4
