### ISSUE TITLE
Reload user metadata

### ISSUE THREAD

**Issue by anandtrex** [jpiepkow/accesspass#47]
Is there a way to reload user meta-data for a logged in user?
I'm specifically interested in reloading the user `confirmed` flag, so that after the user has confirmed their account, they don't have to re-login for the status to update.

If not, what would be the recommended way of adding such support into the library?

**Comment by jpiepkow** [comment]
After a user has confirmed. That route should return new tokens that can be used to access email confirmation protected routes. Just make sure you use those newly returned tokens and you should be good to go. Let me know if this works for you.

**Comment by anandtrex** [comment]
Ok makes sense. Thanks!
