### ISSUE TITLE
Other emailing providers

### ISSUE THREAD

**Issue by abartier** [jpiepkow/accesspass#6]
Hello, 

Thanks for the work you've done so far. 
I strongly believe this is the kind of lib that is missing to get more elixir/phoenix adopters! 

Any plans to support other emailing providers? Mailgun is great but there a lot of other possibilities.

This is more a feature request than a real issue ;)

**Comment by jpiepkow** [comment]
I would love to support more provides, its just a matter of a hex lib being available for them. I may down the road make some adapters for popular requests so that they can be used with accesspass / independent of it. Do you have any provider in specific you are looking to use?

**Comment by abartier** [comment]
Well, we use AWS SES a lot. 

There's a lot of providers for this service supporting them all can be difficult. I believe that a SMTP adapter could be a good start. 

Another possibility could be to add bamboo as a dependency as it already offers a lot of adapters.

**Comment by jpiepkow** [comment]
will be taken care of in #10
