### ISSUE TITLE
Mailgun requiring an old version of poison

### ISSUE THREAD

**Issue by nurges** [jpiepkow/accesspass#9]
Currently mailgun requires poison v1.4 while phoenix uses v2.2 and newer.
The mailgun project also appears to be abandoned.

Maybe it's better to use [Bamboo](https://github.com/thoughtbot/bamboo) instead?

**Comment by jpiepkow** [comment]
This is very interesting @nurges . I will look into it sometime this weekend as I would love to get rid of the override on poison.

**Comment by jpiepkow** [comment]
will be taken care of in #10

**Comment by jpiepkow** [comment]
Updated and version 0.5.0 is on hex to support bamboo as the email adapter
